automator/automator/urls.py
from django.contrib import admin
from django.urls import path,include
from clients.views import pageNotFound
from lotslist.views import *

urlpatterns = [
    path("",include("clients.urls")),
    path('admin/', admin.site.urls),
    path("lotslist/",include("lotslist.urls"))
]

handler404 = pageNotFound

automator/clients/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    path("", index, name="home"),
    path("about/", about, name="about"),
    path("login/", login, name="login"),
    path("contact/", contact, name="contact"),
    path("add_client/", add_client, name="add_client"),
    path("clients_list/", clients_list, name="clients_list"),
    path('show_client/<str:cl_inn>/', show_client, name='show_client'),
    path('find_client/', find_client, name='find_client'),
    path("run-script/", run_script_view, name="run_script"),
    path("edit_client/<str:cl_inn>",edit_client,name = "edit_client"),
    path('delete_client/<str:cl_inn>/', delete_client, name='delete_client'),
    
    path("add_lot/<int:cl_inn>", add_lot, name="add_lot"),
    path("lot_list/", lot_list, name="lot_list"),
    path("edit_lot/<int:id>/",edit_lot,name="edit_lot"),
    path('events/', lot_events, name='lot-events'),
]

automator/lotslist/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    
    # path("add_lot/", add_lot, name="add_lot"),
    path('api/lots/', LotListAPIView.as_view(), name='lot-list-api'),
    
]

automator/lotslist/models.py
from django.db import models
from clients.models import Client

class LotListBank(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name="Клиент")
    lot_efrsb_urls = models.URLField(max_length=200, verbose_name="Ссылка на ЕФРСБ", help_text="Введите ссылку на ЕФРСБ")
    lot_place_urls = models.URLField(max_length=200, verbose_name="Ссылка на местопровеления торга", help_text="Введите ссылку на местоположение лота")
    obligator = models.CharField(max_length=50, verbose_name="Должник", help_text="Имя должника")

    PROCEDURE_TYPE_CHOICES = [
        ('auction', 'Аукцион'),
        ('public_offer', 'Публичное предложение'),
    ]
    proc_type = models.CharField(max_length=20, choices=PROCEDURE_TYPE_CHOICES, verbose_name="Тип процедуры")
    lot_number = models.CharField(max_length=40,verbose_name="введите номера лотов клиента через запятую")
    end_of_feed = models.DateTimeField(verbose_name="Конец подачи заявки")
    auction_day = models.DateTimeField(verbose_name="Дата проведения аукциона")
    total_price = models.DecimalField(max_digits=12, decimal_places=2, verbose_name="Цена лота", blank=True, null=True)

    ACTION_STATUS_CHOICES = [
        ('conducted', 'Проведены'),
        ('not_conducted', 'Не проведены'),
    ]
    action_status = models.CharField(max_length=15, choices=ACTION_STATUS_CHOICES, verbose_name="Статус торгов", blank=True, null=True)

    APPLICATION_STATUS_CHOICES = [
        ('submitted', 'Подано'),
        ('not_submitted', 'Не подано'),
    ]
    feed_status = models.CharField(max_length=13, choices=APPLICATION_STATUS_CHOICES, verbose_name="Статус заявки", blank=True, null=True)

    feed_price = models.DecimalField(max_digits=12, decimal_places=2, verbose_name="Цена заявки")
    price_procent = models.DecimalField(max_digits=5, decimal_places=2, verbose_name="Процент за агентское вознаграждение", blank=True, null=True)

    def __str__(self):
        return f"Лот {self.id} - Клиент {self.client.full_name}"

    class Meta:
        verbose_name = "лоты"
        verbose_name_plural = "Список лотов"

automator/lotslist/forms.py
from django import forms
from .models import LotListBank

class LotForm(forms.ModelForm):
    class Meta:
        model = LotListBank
        fields = '__all__'  # Используйте все поля модели
        exclude = ('client',)

    def __init__(self, *args, **kwargs):
        self.client = kwargs.pop('client', None)
        super().__init__(*args, **kwargs)
        if self.client:
            self.fields['client'].initial = self.client

automator/lotslist/views.py
from django.shortcuts import render, redirect, HttpResponse, redirect,get_object_or_404
from django.http import HttpResponseNotFound, Http404, JsonResponse
from .forms import LotForm  # Убедитесь, что правильно импортировали LotForm
from .models import *
from django.http import JsonResponse
from .models import LotListBank
from .serializers import LotSerializer
from rest_framework import generics

def add_lot(request,cl_inn):
    client = get_object_or_404(Client, cl_inn=cl_inn)
    if request.method == 'POST':
        form = LotForm(request.POST)
        if form.is_valid():
            # Сохраните лот с учетом клиента
            lot = form.save(commit=False)
            lot.client = client
            lot.save()
            return redirect("home")  # Убедитесь, что у вас есть URL с именем 'home' в urls.py
    else:
        form = LotForm()  # Используйте здесь LotForm вместо LotListBank
    
    return render(request, 'lotslist/add_lots.html', {'form': form})


def edit_lot(request, id):
    lot = get_object_or_404(LotListBank, id=id)
    if request.method == "POST":
        form = LotForm(request.POST, instance=lot)
        if form.is_valid():
            form.save()
            return redirect('lotlist') 
    else:
        form = LotForm(instance=lot)
    
    return render(request, 'lotslist/edit_lot.html', {'form': form})


def lot_list(request):
    lots = LotListBank.objects.all()
    context = {'lots':lots,}
    return render(request, "lotslist/lot_list.html", context=context)


# def fetch_lot_efrsb_urls():
#     lots = LotListBank.objects.all()
#     urls = [lot.lot_efrsb_urls for lot in lots]
#     return urls

class LotListAPIView(generics.ListAPIView):
    queryset = LotListBank.objects.all()
    serializer_class = LotSerializer

# не работает:
def lot_events(request):
    lots = LotListBank.objects.all()
    lot_data = [
        {
            'title': f'Лоhт {lot.id}',
            'start': lot.auction_day.strftime('%Y-%m-%d'), # или lot.end_of_feed, в зависимости от того, какую дату вы хотите использовать
            'url': f'/path/to/lot/{lot.id}/'  # Ссылка для просмотра деталей лота
        } for lot in lots
    ]
    return JsonResponse(lot_data, safe=False)

automator/templates/lotslist/add_lots.html
{% extends "base.html" %}

{% block content %}
<!-- <a href="{% url 'home' %}"><button>вернуться на главную</button></a>
<a href="{% url 'clients_list' %}"><button>список клиентов</button></a> -->
<title>Доюавить лот</title>
</head>

<body>
    <h2>Заполните форму</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
    {% if form.errors %}
    <ul>
        {% for field in form %}
        {% for error in field.errors %}
        <li><strong>{{ field.label }}:</strong> {{ error }}</li>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <li><strong>Общая ошибка:</strong> {{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% endblock %}

automator/templates/lotslist/edit_lot.html
{% extends "base.html" %}

{% block content %}
  <h2>Редактирование лота</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить изменения</button>
  </form>
{% endblock %}

automator/templates/lotslist/lot_list.html
{% extends "base.html" %}
{% block content %}
<h1>Список лотов</h1>

<table border = 1>
    <thead>
        <tr>
            <th>ID лота</th>
            <th>Клиент</th>
            <th>Ссылка на ЕФРСБ</th>
            <th>Номер лотов клиента</th>
            <th>Местопроведение торга</th>
            <th>Действие</th>
            <th>Тип процедуры</th>
            <th>Конец подачи заявки</th>
            <th>Дата аукциона</th>
            <th>Цена лота</th>
            <th>Статус торгов</th>
            <th>Статус заявки</th>
            <th>Цена заявки</th>
            <th>Процент за вознаграждение</th>
        </tr>
    </thead>
    <tbody>
        {% for lot in lots %}
        <tr>
            <td>{{ lot.id }}</td>
            <td><a href="{% url 'show_client' cl_inn=lot.client.cl_inn %}">{{ lot.client.full_name }}</a></td> <!-- Предполагается, что у клиента есть поле full_name -->
            <td><a href="{{ lot.lot_efrsb_urls }}">Ссылка</a></td>
            <td>{{ lot.lot_number }}</td>
            <td><a href="{{ lot.lot_place_urls }}">Ссылка</a></td>
            <td><a href="{% url 'edit_lot' lot.id %}">редактировать запись</a></td>
            <td>{{ lot.get_proc_type_display }}</td>
            <td>{{ lot.end_of_feed }}</td>
            <td>{{ lot.auction_day }}</td>
            <td>{{ lot.total_price }}</td>
            <td>{{ lot.get_action_status_display }}</td>
            <td>{{ lot.get_feed_status_display }}</td>
            <td>{{ lot.feed_price }}</td>
            <td>{{ lot.price_procent }}%</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}